apiVersion: v1
kind: List
metadata:
  name: hello-openshift
items:
- kind: ImageStream
  apiVersion: image.openshift.io/v1
  metadata:
    name: hello-openshift
    labels:
      app: hello-openshift
- kind: BuildConfig
  apiVersion: build.openshift.io/v1
  metadata:
    name: hello-openshift
    labels:
      app: hello-openshift
      app.kubernetes.io/component: hello-openshift
      app.kubernetes.io/instance: hello-openshift
      app.kubernetes.io/name: hello-openshift
      app.kubernetes.io/part-of: hello-openshift
      app.openshift.io/runtime: java
  spec:
    output:
      to:
        kind: ImageStreamTag
        name: 'hello-openshift:latest'
    strategy:
      type: Source
      sourceStrategy:
        from:
          kind: ImageStreamTag
          namespace: openshift
          name: 'redhat-openjdk18-openshift:1.5'
    source:
      type: Git
      git:
        uri: 'https://github.com/leandroberetta/hello-openshift.git'
- apiVersion: build.openshift.io/v1
  kind: BuildConfig
  metadata:
    labels:
      app: hello-openshift-pipeline
    name: hello-openshift-pipeline
  spec:
    source:
      git:
        ref: master
        uri: https://github.com/leandroberetta/hello-openshift.git
      type: Git
    strategy:
      jenkinsPipelineStrategy:
        jenkinsfilePath: Jenkinsfile
      type: JenkinsPipeline